hkjc:
  jms:
    queue:
      sub: sts/translation/pending
  msg: '{
      "accountNo": 12343534,
      "channelId": 7,
      "sessionId": "abc123",
      "translatedDto": [
        {
          "betType": {
            "eng": "Win",
            "chi": "獨贏",
            "raw": "WIN"
          },
          "detail": {
            "eng": "Sha Tin WED Win Race 1 \n\t1 ELUSIVE STATE + 2 DANCES WITH DRAGON + \n\t3 DARK DREAM $10",
            "chi": "沙田 星期三 獨贏 第1場 \n\t1 烽煙四喜 + 2 與龍共舞 + \n\t3 達龍駒 $10",
            "longBetLine": "ST WED WIN 1*1+2+3 $10",
            "checksum": "134343"
          },
          "totalAmount": "10"
        },
        {
          "betType": {
            "eng": "Place",
            "chi": "位置",
            "raw": "PLA"
          },
          "detail": {
            "eng": "Sha Tin WED Place Race 2 \n\t1 CHEFANO + 2 GLORIOUS DRAGON $10",
            "chi": "沙田 星期三 位置 第2場 \n\t1 任我行 + 2 龍鼓飛揚 $10",
            "longBetLine": "ST WED WIN 1*1+2+3 $10",
            "checksum": "134343"
          },
          "totalAmount": "10"
        }
      ]
    }'

solace:
  jms:
    host: tcp://10.194.117.223:55555
    msgVpn: csp_poc
    clientUsername: tempuser
    clientPassword: "00000000"



